### ISSUE TITLE
Create Table if doesn't exist

### ISSUE THREAD

**Issue by markman123** [chrishanel/uecker-bot#6]
# Overview
The `DELETE` statement precedes checking if table exists and creation
## Error
```bash
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: games
[SQL: DELETE FROM games WHERE id IN (SELECT id FROM tmp);]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by markman123** [comment]
@reddigari is there a way to run db.py first? I think that creates the schema if missing?

EDIT: asking as I don't know, no assumption you'll Just Do It™️

**Comment by reddigari** [comment]
Yeah I wrote it assuming the DB schema had been created (since we're passing in a DB URI to sqlalchemy). You can just run `python db.py` from the top-level and it'll create everything for you (delete `main.db` first if it exists). I then recommend moving the DB file into pipeline so you can run the scripts from there without changing any environment variables.

So my pipeline directory now looks like:
```
uecker-bot on  main [?] via  v3.7.3
❯ tree pipeline
pipeline
├── main.db
├── output
│   ├── outcomes_2022-03-20.csv
│   ├── outcomes_2022-03-26.csv
│   ├── outcomes_2022-03-28.csv
│   ├── schedule_2022-03-20.csv
│   ├── schedule_2022-03-26.csv
│   └── schedule_2022-03-28.csv
├── scrape_data.py
└── update_db.py
```
1 directory, 9 files

**Comment by markman123** [comment]
easy, thanks for that! will close given no issue here
